services:
  # users-service:
  #   build: ./
  #   container_name: users-service
  #   hostname: users-service
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5000:5000
  #   image: users-service
  #   depends_on:
  #     users_pgdb:
  #       condition: service_healthy
  #   networks:
  #     - users_net

  users_pgdb:
    container_name: users_pgdb
    hostname: users_pgdb
    image: postgres:16.2-alpine
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: users
      PGPASSWORD: admin
      PGUSER: users
      PGDATABASE: usersdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/data
      - ./docker/postgresql-init:/docker-entrypoint-initdb.d
    networks:
      - users_net

networks:
  users_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24