services:
  # products-service:
  #   build: ./
  #   container_name: products-service
  #   hostname: products-service
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5000:5000
  #   image: products-service
  #   depends_on:
  #     products_pgdb:
  #       condition: service_healthy
  #   networks:
  #     - products_net

  products_pgdb:
    container_name: products_pgdb
    hostname: products_pgdb
    image: postgres:16.2-alpine
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: products
      PGPASSWORD: admin
      PGUSER: products
      PGDATABASE: productsdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/data
      - ./docker/postgresql-init:/docker-entrypoint-initdb.d
    networks:
      - products_net

networks:
  products_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24